/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kopikopi;

import java.awt.event.*;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author alanmsmxyz
 */
public class ViewCustomer extends javax.swing.JFrame {

    /**
     * Creates new form CustomerView
     */
    public ViewCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCustomer = new javax.swing.JPanel();
        labelOrderMenu = new javax.swing.JLabel();
        selectOrder = new javax.swing.JComboBox<>();
        labelOrderQty = new javax.swing.JLabel();
        inputOrderQty = new javax.swing.JTextField();
        btnAddItem = new javax.swing.JButton();
        btnRemoveItem = new javax.swing.JButton();
        containerTableOrderItems = new javax.swing.JScrollPane();
        tableOrderItems = new javax.swing.JTable();
        labelOrderTotal = new javax.swing.JLabel();
        inputOrderTotal = new javax.swing.JTextField();
        btnConfimOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelOrderMenu.setText("Pilih Kopi");

        labelOrderQty.setText("Jumlah");

        inputOrderQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputOrderQtyActionPerformed(evt);
            }
        });

        btnAddItem.setText("Tambah ke Order");

        btnRemoveItem.setText("Hapus dari Order");

        tableOrderItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kopi", "Jumlah", "Hagra", "Total"
            }
        ));
        containerTableOrderItems.setViewportView(tableOrderItems);

        labelOrderTotal.setText("Total");

        inputOrderTotal.setEditable(false);
        inputOrderTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputOrderTotalActionPerformed(evt);
            }
        });

        btnConfimOrder.setText("Konfirmasi Order");
        btnConfimOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfimOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCustomerLayout = new javax.swing.GroupLayout(panelCustomer);
        panelCustomer.setLayout(panelCustomerLayout);
        panelCustomerLayout.setHorizontalGroup(
            panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustomerLayout.createSequentialGroup()
                        .addComponent(selectOrder, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputOrderQty, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelOrderQty)))
                    .addGroup(panelCustomerLayout.createSequentialGroup()
                        .addComponent(btnAddItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemoveItem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCustomerLayout.createSequentialGroup()
                        .addComponent(labelOrderMenu)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(containerTableOrderItems, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustomerLayout.createSequentialGroup()
                        .addComponent(labelOrderTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(inputOrderTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustomerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnConfimOrder)))
                .addContainerGap())
        );
        panelCustomerLayout.setVerticalGroup(
            panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOrderMenu)
                    .addComponent(labelOrderQty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputOrderQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddItem)
                    .addComponent(btnRemoveItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(containerTableOrderItems, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputOrderTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelOrderTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfimOrder)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputOrderQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputOrderQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputOrderQtyActionPerformed

    private void inputOrderTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputOrderTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputOrderTotalActionPerformed

    private void btnConfimOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfimOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfimOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnConfimOrder;
    private javax.swing.JButton btnRemoveItem;
    private javax.swing.JScrollPane containerTableOrderItems;
    private javax.swing.JTextField inputOrderQty;
    private javax.swing.JTextField inputOrderTotal;
    private javax.swing.JLabel labelOrderMenu;
    private javax.swing.JLabel labelOrderQty;
    private javax.swing.JLabel labelOrderTotal;
    private javax.swing.JPanel panelCustomer;
    private javax.swing.JComboBox<String> selectOrder;
    private javax.swing.JTable tableOrderItems;
    // End of variables declaration//GEN-END:variables

    // Reset view
    public void clearOrder() {
        resetOrderInput();
        resetOrderItems();
        resetOrderTotal();
    }
    
    // Set available coffee to be selected
    public void setSelection(String[] s) {
        selectOrder.setModel(new javax.swing.DefaultComboBoxModel<>(s));
    }

    // Order input overalls, controlling value of selectOrder adn inputOrderQty
    public void updateOrderInput(Object order, int qty) {
        selectOrder.setSelectedItem(order);
        inputOrderQty.setText(String.valueOf(qty));
    }
    
    public void resetOrderInput() {
        selectOrder.setSelectedIndex(-1);
        inputOrderQty.setText("");
    }
    
    // Methods to gather user input
    public Object getSelectedOrder() {
        return selectOrder.getSelectedItem();
    }
    
    public int getSelectedOrderQty() {
        return Integer.parseInt(inputOrderQty.getText());
    }
    
    // Order items table, controling content of the table
    public void resetOrderItems() {
        DefaultTableModel model = (DefaultTableModel) tableOrderItems.getModel();
        model.getDataVector().clear();
    }

    public void updateOrderItems(Object[][] content) {
        DefaultTableModel model = (DefaultTableModel) tableOrderItems.getModel();
        model.setDataVector(
                content,
                new String[]{
                    "Kopi", "Jumlah", "Hagra", "Total"
                }
        );
    }
    
    // Order total    
    public void resetOrderTotal() {
        inputOrderTotal.setText("");
    }
    
    public void updateOrderTotal(int total) {
        inputOrderTotal.setText(String.valueOf(total));
    }
     
    // Method to identify action source in handler classes
    public JButton getBtnAddOrder() {
        return btnAddItem;
    }

    public JButton getBtnRemoveOrder() {
        return btnRemoveItem;
    }

    public JTable getTableOrder() {
        return tableOrderItems;
    }
    
    // Binding ActionListener & MouseListener
    public void addActionListener(ActionListener e) {
        btnAddItem.addActionListener(e);
        btnRemoveItem.addActionListener(e);
    }

    public void addMouseAdapter(MouseListener e) {
        tableOrderItems.addMouseListener(e);
    }
}
