/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kopikopi;

import java.awt.event.*;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author alanmsmxyz
 */
public class ViewAdmin extends javax.swing.JFrame {

    /**
     * Creates new form CustomerView
     */
    public ViewAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAdmin = new javax.swing.JPanel();
        labelMenuName = new javax.swing.JLabel();
        inputMenuName = new javax.swing.JTextField();
        labelMenuPrice = new javax.swing.JLabel();
        inputMenuPrice = new javax.swing.JTextField();
        btnAddMenu = new javax.swing.JButton();
        btnRemoveMenu = new javax.swing.JButton();
        containerTableMenuList = new javax.swing.JScrollPane();
        tableMenuList = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelMenuName.setText("Nama Kopi");

        labelMenuPrice.setText("Harga");

        inputMenuPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMenuPriceActionPerformed(evt);
            }
        });

        btnAddMenu.setText("Tambah ke Menu");

        btnRemoveMenu.setText("Hapus dari Menu");

        tableMenuList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Kopi", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        containerTableMenuList.setViewportView(tableMenuList);

        javax.swing.GroupLayout panelAdminLayout = new javax.swing.GroupLayout(panelAdmin);
        panelAdmin.setLayout(panelAdminLayout);
        panelAdminLayout.setHorizontalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdminLayout.createSequentialGroup()
                        .addComponent(btnAddMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemoveMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(containerTableMenuList, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminLayout.createSequentialGroup()
                        .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAdminLayout.createSequentialGroup()
                                .addComponent(labelMenuName)
                                .addGap(0, 189, Short.MAX_VALUE))
                            .addComponent(inputMenuName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMenuPrice)
                            .addComponent(inputMenuPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelAdminLayout.setVerticalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMenuName)
                    .addComponent(labelMenuPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputMenuPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputMenuName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMenu)
                    .addComponent(btnRemoveMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(containerTableMenuList, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputMenuPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMenuPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMenuPriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMenu;
    private javax.swing.JButton btnRemoveMenu;
    private javax.swing.JScrollPane containerTableMenuList;
    private javax.swing.JTextField inputMenuName;
    private javax.swing.JTextField inputMenuPrice;
    private javax.swing.JLabel labelMenuName;
    private javax.swing.JLabel labelMenuPrice;
    private javax.swing.JPanel panelAdmin;
    private javax.swing.JTable tableMenuList;
    // End of variables declaration//GEN-END:variables

    // Order input overalls, controlling value of selectOrder adn inputOrderQty
    public void updateMenuInput(String name, String price) {
        inputMenuName.setText(name);
        inputMenuPrice.setText(price);
    }
    
    public void resetMenuInput() {
        inputMenuName.setText("");
        inputMenuPrice.setText("");
    }
    
    // Methods to gather user input
    public String getMenuName() {
        return inputMenuName.getText();
    }
    
    public int getMenuPrice() {
        return Integer.parseInt(inputMenuPrice.getText());
    }
    
    // Order items table, controling content of the table
    public void resetMenuList() {
        DefaultTableModel model = (DefaultTableModel) tableMenuList.getModel();
        model.getDataVector().clear();
    }

    public void updateMenuList(Object[][] content) {
        DefaultTableModel model = (DefaultTableModel) tableMenuList.getModel();
        model.setDataVector(
                content,
                new String[]{
                    "Kopi", "Hagra"
                }
        );
    }
     
    // Method to identify action source in handler classes
    public JButton getBtnAddMenu() {
        return btnAddMenu;
    }

    public JButton getBtnRemoveMenu() {
        return btnRemoveMenu;
    }

    public JTable getTableMenuList() {
        return tableMenuList;
    }
    
    // Binding ActionListener & MouseListener
    public void addActionListener(ActionListener e) {
        btnAddMenu.addActionListener(e);
        btnRemoveMenu.addActionListener(e);
    }

    public void addMouseAdapter(MouseListener e) {
        tableMenuList.addMouseListener(e);
    }
}
